[pytest]
testpaths = tests/ui tests/api

addopts = --html=reports/report.html --self-contained-html --alluredir=allure-results

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    ui: UI 자동화 테스트 (Selenium)
    api: API 자동화 테스트 (requests)
