[pytest]
# 2. 테스트를 찾을 기본 경로 지정 (tests 폴더 안에서만 찾도록 제한)
testpaths = tests/api tests/ui tests/tc

# 3. 로깅(Logging) 포맷 설정
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
<<<<<<< HEAD
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    ui: UI 테스트
=======
log_cli_date_format = %Y-%m-%d %H:%M:%S
>>>>>>> a8bf63ac44ca414e419e91a36b0075aa7fbcb21f
